---
title: "Avocados"
author: "Maria Freydlin"
date: "4/16/2021"
output: slidy_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

```{r, eval=FALSE, message=FALSE, warning=FALSE}
df <- read.csv("List_of_countries_by_avocado_production.csv")

library(plotly)
library(dplyr)
library(ggplot2)

df8 <- df[1:8,]

names(df8)[2:5]=c('Country',  '2018', '2017','2016')



library(tidyr)
avocados = pivot_longer(df8, cols = 3:5, names_to = 'year', values_to = 'volume')

g <- ggplot(avocados, aes(year, volume)) +
        geom_bar(stat='identity', position='dodge', aes(fill=Country))+
        scale_fill_discrete(name = "Country")+
        ggtitle("Avocado Production")


(gg <- ggplotly(g))

```

## Avocado Production graph created on 4/16/2021

```{r, echo=FALSE, message=FALSE,warning=FALSE}
df <- read.csv("List_of_countries_by_avocado_production.csv")

library(plotly)
library(dplyr)
library(ggplot2)

df8 <- df[1:8,]

names(df8)[2:5]=c('Country',  '2018', '2017','2016')



library(tidyr)
avocados = pivot_longer(df8, cols = 3:5, names_to = 'year', values_to = 'volume')

g <- ggplot(avocados, aes(year, volume)) +
        geom_bar(stat='identity', position='dodge', aes(fill=Country))+
        scale_fill_discrete(name = "Country")+
        ggtitle("Avocado Production")


(gg <- ggplotly(g))


```
